# Generated by Django 5.0.7 on 2024-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldstudents',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
