# Generated by Django 5.0.7 on 2024-07-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldstudents',
            old_name='date_Left',
            new_name='date_left',
        ),
    ]
